name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run build

      - name: Run
        run: npm run start
